---
- name: Installs Gerrit Code Review
  hosts: gerrit-ubuntu-servers
  sudo: true
 
  vars:
    # custom smtp configuration
    gerrit_custom_smtp: true
    gerrit_sendemail_smtp_server: 'smtp.office365.com'
    gerrit_smtp_port: 587
    gerrit_smtp_encryption_medhod: 'tls'
    gerrit_smtp_username: 'devopssmtp@audiocodes.com'
    gerrit_smtp_password: 'ilov3AWScloud$' # need to encrypt !
    gerrit_mail_from_addr: 'gerrit@audiocodes.com'
    # session expiration ... 
    gerrit_web_sessions_maxage: '1 year'

  roles:
    - dns
    - kbrebanov.gerrit
  tasks:
