---
- name: Installs ipp compilation server 
  hosts: ipp-compilation-servers
  sudo: true
 
  vars:
    - ansible_ssh_user: root
    - ansible_distribution: CentOS
    - dns_nameservers: ['8.8.8.8','8.8.4.4','10.1.1.11','10.1.1.10']

  roles:
    - dns
    - williamyeh.oracle-java
    - kbrebanov.unzip
    - bzip2
#    - docker
    - ipp
  tasks:
