---
- name: Installs Jenkins CI server
  hosts: jenkins-servers
  sudo: true
   	
  vars:
    - ansible_ssh_user: centos

  roles:
    - dns
    - kbrebanov.git
    - geerlingguy.jenkins
    - { role: docker, docker_remove: true, }
